# development
system:
  # url前缀
  url-path-prefix: api
  # 程序监听端口
  port: 10000
  # 是否开启redis
  use-redis: true
  # 开启全局事务管理器
  transaction: true
  # 是否初始化数据(没有初始数据时使用, 已发布正式版谨慎使用)
  init-data: false
  # 操作日志key
  operation-log-key: operation_log_response
  # rsa公钥文件路径
  rsa-public-key: /Users/piupuer/eric/learning/gin-web/conf/gin-web-rsa.pub
  # rsa私钥文件路径
  rsa-private-key: /Users/piupuer/eric/learning/gin-web/conf/gin-web-rsa

logs:
  # 日志等级(-1:Debug, 0:Info, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 100
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false

mysql:
  # 用户名
  username: root
  # 密码
  password: root
  # 数据库名
  database: gin_web
  # 主机地址(地址改为docker内网地址, 参见gin-web-docker项目docker-compose.yml配置)
  host: docker-mysql-db
  # 端口
  port: 3306
  # 连接字符串查询参数
  query: charset=utf8&parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: false
  # 数据库表前缀
  table-prefix: tb_

redis:
  # 主机地址(地址改为docker内网地址, 参见gin-web-docker项目docker-compose.yml配置)
  host: 127.0.0.1
  # 端口
  port: 5556
  # 密码(默认为空)
  password:
  # 数据库编号
  database: 0
  # binlog位置缓存键
  binlog-pos: mysql_binlog_pos

# casbin配置
casbin:
  # 模型配置文件, 默认以conf目录为根目录
  model-path: 'rbac_model.conf'

# jwt配置
jwt:
  # jwt标识
  realm: test jwt
  # 服务端密钥
  key: secret key
  # token过期时间, 小时
  timeout: 24
  # token更新时间, 小时
  max-refresh: 24

# 速率限制配置
rate-limit:
  # 访问最大限制, 次/秒
  max: 200

# 上传配置
upload:
  # 上传文件保存路径
  save-dir: upload
  # 单个文件或分片文件最大限制, 单位MB(上传文件先读取到内存, 如果这个值设置过大会导致内存崩溃)
  single-max-size: 32
  # 合并文件并发数(并发合并文件会提升性能, 但如果设置过大性能降低, 结合实际机器性能配置)
  merge-concurrent-count: 10
